spring.application.name=hibernateJPACrudApplication
spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker
spring.datasource.username=user
spring.datasource.password=password

#turn off the spring boot banner
spring.main.banner-mode=off

#reduce logging level
#warn will show only warn and error message
logging.level.root=warn

# create = JPA will drop the table and create
# update = only update database
spring.jpa.hibernate.ddl-auto=update